#!/usr/bin/env bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

xset s off

# Update functions
update_cpu() {
  cpu=$(awk '{print $1}' /proc/loadavg)
}

update_memory() {
  memory=$(free -h | awk 'NR==2 {print $3}')
}

update_time() {
  time=$(date "+%b %d %H:%M ")
}

update_ip() {
  ip_address=$(hostname -I | awk '{print $1}')
}

# Display function
display() {
  status=""
  [[ -n "$cpu" ]] && status+="  CPU: $cpu | "
  [[ -n "$memory" ]] && status+=" RAM: $memory | "
  [[ -n "$ip_address" ]] && status+=" IP: $ip_address | "
  [[ -n "$time" ]] && status+=" $time"
  xsetroot -name "$status"
}

# Set up signal handlers
trap "update_cpu; display" "RTMIN"
trap "update_memory; display" "RTMIN+1"
trap "update_ip; display" "RTMIN+2"

# Initial updates
update_cpu
update_memory
update_ip

# Main loop
while true; do
  sleep 1
  sec=$((sec + 1))
  case $((sec % 300)) in
    0)
      echo "Cambiando fondo de pantalla..."
      feh --randomize --bg-fill /home/ginger/Pictures/backgrounds/
      ;;
  esac

  case $((sec % 60)) in
    *)
      update_time
      update_cpu
      update_memory
      update_ip
      display
      ;;
  esac
done
